services:
- type: web
  name: rabbitmq
  env: docker

  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: RABBITMQ_DEFAULT_USER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: true

  # see: https://github.com/docker-library/rabbitmq/issues/171
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq/mnesia
    sizeGB: 10
