services:
- type: web
  name: rabbitmq
  env: docker
  envVars:
  - key: RABBITMQ_ERLANG_COOKIE
    generateValue: true
  - key: RABBITMQ_DEFAULT_USER
    value: rabbitmq
  - key: RABBITMQ_DEFAULT_PASS
    generateValue: true
  disk:
    name: rabbitmq
    mountPath: /var/lib/rabbitmq/mnesia # see: https://github.com/docker-library/rabbitmq/issues/171
    sizeGB: 10
  dockerCommand: >
    /bin/bash -lc 'chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/mnesia &&
                   exec docker-entrypoint.sh rabbitmq-server'